# docker-compose.yml
services:
  library-app:
    build: .
    container_name: library-db
    volumes:
      - ./app/data:/app/data
      - ./app:/app/app
      - ./.env:/app/.env
    environment:
      - DB_PATH=/app/data/library.db
      - DB_ECHO=False
      - PYTHONUNBUFFERED=1
    stdin_open: true
    tty: true